apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-ingest
  name: udaconnect-location-ingest
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: udaconnect-location-ingest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-ingest
  name: udaconnect-location-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-ingest
  template:
    metadata:
      labels:
        service: udaconnect-location-ingest
    spec:
      containers:
      - image: supirman/udaconnect-location-ingest:latest
        name: udaconnect-location-ingest
        imagePullPolicy: Always
        env:
      restartPolicy: Always
